name: github action demo

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.head_ref}}
    
    - name: set up python 3.8
      uses: actions/setup-python@v1
      with:
         python-version: 3.8.*
    
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    
    - name: Cache pipenv virtualenv
      id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: /opt/tool/Python/
        key: ${{ runner.os }}-pipenv-${{ hashFiles('requirements.txt') }}

    - name: upgrade pip
      run: |
            pip install --upgrade pip

    - name: install requirements
      run: |
           pip install -r requirements.txt
