name: github action demo

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.head_ref}}
    
    - name: set up python 3.8
      uses: actions/setup-python@v1
      with:
         python-version: 3.8.*
