
name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      -run: echo "job was automatically triggered by a ${{ github.event_name}} event."
      -run: echo "This job is now running on a ${{ runner.os}} server hosted by github"
      -run: echo "The name of your branch is ${{github.ref}} and your repository is ${{ github.repository}}."
      -name: Check out the code
       uses: actions/checkout@v2
      -name: List files in the repo
       run: |
        ls ${{github.workspace}}
      -run: echo "This job status is ${{job.status}}."